### ISSUE TITLE
Deploy api

### ISSUE THREAD

**Issue by SandersAaronD** [grafana/ai-training-o11y#45]
- [x] ci pipeline to create and push images
- [x] sql instance
- [x] create deployment manifests for backend
- [x] cortex gateway
- [x] add public endpoint (LB/DNS/...)
- [x] loki dev tenant (add secrets to vault, etc)
- [ ] RED metrics

**Comment by annanay25** [comment]
closing this as all infra components are in place now. will create follow up PRs as needed.
![image](https://github.com/user-attachments/assets/600b8283-24b4-4848-9ef9-01ae69295848)

**Comment by annanay25** [comment]
thanks to @csmarchbanks for all the pairing!
